application: saadiyatgames
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bootstrap/css
  static_dir: bootstrap/css
- url: /(.*\.(gif|png|jpg))
  static_files: static/\1 
  upload: static/(.*\.(gif|png|jpg))
- url: /images
  static_dir: images
  mime_type: image/jpg
- url: /.*
  script: saad.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
